git:
  log:
    showGraph: always
    showWholeGraph: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never

keybinding:
  commits:
    moveUpCommit: <c-q>
    moveDownCommit: <c-a>
    openLogMenu: <c-g>
