#!/usr/bin/env zsh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

PADDINGS=5 # All paddings use this value (icon, label, background)
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
SHADOW=on
FONT_FACE="MesloLGS Nerd Font Mono"

# Setting up the general bar appearance and default values
sketchybar --bar     height=32        \
                     blur_radius=30   \
                     position=top     \
                     sticky=on        \
                     padding_left=10  \
                     padding_right=10 \
                     color=$BAR_COLOR \
                                                                       \
           --default updates=when_shown                                \
                     icon.color=$ICON_COLOR                            \
                     icon.font.family="$FONT_FACE"                     \
                     icon.font.size=25                                 \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.color=$LABEL_COLOR                          \
                     label.font.family="$FONT_FACE"                    \
                     label.font.size=14                                \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/current_space.sh"
source "$ITEM_DIR/slack.sh"
source "$ITEM_DIR/aerospace.sh"

# Center

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/keyboard.sh"


##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
