#!/usr/bin/env bash

# Find and pick dotfiles for quick edit
selected=$(
    fd --type f --hidden --exclude .git . ~/work/other/dotfiles | 
    fzf --preview "bat --color=always --style=numbers {}" --header "Select a file to edit"
)

if [ -z "$selected" ]; then
    exit 0
fi

$EDITOR $selected

