#!/bin/zsh

# This script creates a new note in the Obsidian vault with the current date and the provided name.

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. on \"the wonderful thing about tiggers\"."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
cd "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/vault_1" || exit
touch "inbox/${formatted_file_name}"
nvim "inbox/${formatted_file_name}"

