#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    select_options=()
    while IFS= read -rd '' dir; do
        select_options+=("$dir")
    done < <(
        find ~/work/other -mindepth 1 -maxdepth 1 -type d -print0
        find ~/work/gamedev -mindepth 1 -maxdepth 1 -type d -print0
        find ~/work/exness -mindepth 1 -maxdepth 2 -type d -print0
        find ~/work/arduino -mindepth 1 -maxdepth 1 -type d -print0
        find ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents -mindepth 1 -maxdepth 1 -type d -print0
    )
    selected=$(printf "%s\n" "${select_options[@]}" | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
# Add "Obsidian" to the name if the selected directory is in the iCloud folder
if [[ $selected == *iCloud~md~obsidian* ]]; then
    selected_name="Obsidian_$selected_name"
fi
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
